import = [
  "~/.config/alacritty/hotanphat.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
opacity = 0.9
blur = true

[font]
size = 13.0

[font.bold]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"
